name: proyectotransferido
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0+2
  cloud_firestore: ^4.14.0
  dotenv: ^4.2.0
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  firebase_ui_auth: ^1.13.0
  firebase_storage: ^11.6.0
  flutter_dotenv: ^5.1.0
  flutter_image_compress: ^2.3.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_map_marker_cluster_2: ^1.0.4
  google_fonts: ^6.2.1
  intl: ^0.19.0
  location: ^7.0.0
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  fluttertoast: ^8.2.8
  geolocator: ^12.0.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - .env
