// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwsy-rQbnLbdRAmgVinqJOdeGlPXpg4zQ',
    appId: '1:362002309084:web:32f643c40567b4573f7919',
    messagingSenderId: '362002309084',
    projectId: 'proyecto-de-titulo-87230',
    authDomain: 'proyecto-de-titulo-87230.firebaseapp.com',
    databaseURL: 'https://proyecto-de-titulo-87230-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-de-titulo-87230.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCW_43LWDDqQPwX-ZNdw0TQ0sJ3mOKst5M',
    appId: '1:362002309084:android:3787bf5dca12f18e3f7919',
    messagingSenderId: '362002309084',
    projectId: 'proyecto-de-titulo-87230',
    databaseURL: 'https://proyecto-de-titulo-87230-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-de-titulo-87230.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkjnHCo6h2cib-AlDOYGsryven1I3FZYA',
    appId: '1:362002309084:ios:ff61a7fb4d7688433f7919',
    messagingSenderId: '362002309084',
    projectId: 'proyecto-de-titulo-87230',
    databaseURL: 'https://proyecto-de-titulo-87230-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-de-titulo-87230.appspot.com',
    iosBundleId: 'com.example.proyectotransferido',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkjnHCo6h2cib-AlDOYGsryven1I3FZYA',
    appId: '1:362002309084:ios:ff61a7fb4d7688433f7919',
    messagingSenderId: '362002309084',
    projectId: 'proyecto-de-titulo-87230',
    databaseURL: 'https://proyecto-de-titulo-87230-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-de-titulo-87230.appspot.com',
    iosBundleId: 'com.example.proyectotransferido',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwsy-rQbnLbdRAmgVinqJOdeGlPXpg4zQ',
    appId: '1:362002309084:web:2d96d5bed98a0c713f7919',
    messagingSenderId: '362002309084',
    projectId: 'proyecto-de-titulo-87230',
    authDomain: 'proyecto-de-titulo-87230.firebaseapp.com',
    databaseURL: 'https://proyecto-de-titulo-87230-default-rtdb.firebaseio.com',
    storageBucket: 'proyecto-de-titulo-87230.appspot.com',
  );
}
